apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    ver: "1.16.0"
    fruta: banana
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector: 
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          requests:
            cpu: "0.5"
            memory: "64Mi"
          limits:
            cpu: "0.7"
            memory: "128Mi"
