apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     protocol: TCP
     targetPort: 5432
     nodePort: 31500
  selector:
   app: postgres
