---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-http
spec:
  selector:
    matchLabels:
      app: httpd
  serviceName: "httpd-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
          name: web
