apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    resources:
      requests:
        cpu: "0.5"
        memory: "64Mi"
      limits: 
        cpu: "1"
        memory: "128Mi"
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}