apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    resources:
      requests:
        cpu: "0.3"
        memory: "64Mi"
      limits: 
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}