apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver-with-busybox
  name: webserver-with-busybox
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: "0.3"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"
  - image: busybox
    name: busybox
    args:
    - sleep
    - "3600"
    resources:
      requests:
        cpu: "0.3"
        memory: "64Mi"
      limits: 
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}