apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2021-12-14T18:03:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elk-master
  name: elk-master-elk-master-0
  namespace: elk
  resourceVersion: "340946947"
  selfLink: /api/v1/namespaces/elk/persistentvolumeclaims/elk-master-elk-master-0
  uid: 173f4e5d-cb96-4496-8b99-5b425931177a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
  volumeName: pvc-173f4e5d-cb96-4496-8b99-5b425931177a
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 400Gi
  phase: Bound