apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2021-12-14T18:03:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elk-master
  name: elk-master-elk-master-2
  namespace: elk
  resourceVersion: "340945810"
  selfLink: /api/v1/namespaces/elk/persistentvolumeclaims/elk-master-elk-master-2
  uid: 2cda88c8-2d04-4c88-b276-5d6c217e7589
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
  volumeName: pvc-2cda88c8-2d04-4c88-b276-5d6c217e7589
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 400Gi
  phase: Bound