apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elk-master
  name: elk-master-elk-master-1
  namespace: elk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound