apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-elk-master-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elk-master-elk-master-1
    namespace: elk
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-9f11e972-81bd-4f10-a87e-d143233f5b07
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
status:
  phase: Bound