apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-elk-master-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elk-master-elk-master-0
    namespace: elk
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-173f4e5d-cb96-4496-8b99-5b425931177a
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
status:
  phase: Bound