apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    app: node-exporter
  type: LoadBalancer
  ports:
  - name: http
    port: 9100
    targetPort: 9100
    nodePort: 31000
