apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: grafana-pv-volume
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-pv-claim
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      