apiVersion: v1
kind: Pod
metadata:
  name: dns-dexter
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.96.0.10
      - 200.100.50.200
      - 8.8.8.8
    searches:
      - default.svc.cluster.local
      - dexter.com.br
    options:
      - name: edns0
  restartPolicy: Always
