apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
  creationTimestamp: "2021-12-14T18:03:47Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-9f11e972-81bd-4f10-a87e-d143233f5b07
  resourceVersion: "340945660"
  selfLink: /api/v1/persistentvolumes/pvc-9f11e972-81bd-4f10-a87e-d143233f5b07
  uid: 166aba3f-ba4c-4ddc-826f-5db9de041a8d
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 400Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elk-master-elk-master-1
    namespace: elk
    resourceVersion: "222682717"
    uid: 9f11e972-81bd-4f10-a87e-d143233f5b07
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      storage.kubernetes.io/csiProvisionerIdentity: 1639403834785-8081-driver.longhorn.io
    volumeHandle: pvc-9f11e972-81bd-4f10-a87e-d143233f5b07
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
status:
  phase: Bound
