apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
  creationTimestamp: "2021-12-14T18:03:49Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-2cda88c8-2d04-4c88-b276-5d6c217e7589
  resourceVersion: "340945809"
  selfLink: /api/v1/persistentvolumes/pvc-2cda88c8-2d04-4c88-b276-5d6c217e7589
  uid: af80d0d7-eac8-45eb-91b7-1614559577d8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 400Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elk-master-elk-master-2
    namespace: elk
    resourceVersion: "222682730"
    uid: 2cda88c8-2d04-4c88-b276-5d6c217e7589
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      storage.kubernetes.io/csiProvisionerIdentity: 1639403834785-8081-driver.longhorn.io
    volumeHandle: pvc-2cda88c8-2d04-4c88-b276-5d6c217e7589
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-noreplication
  volumeMode: Filesystem
status:
  phase: Bound
