apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pool: lento
  name: meu-pv-lento
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  storageClassName: meu-storage