apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pool: nfs
  name: meu-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.200
    path: /var/nfs/general
  storageClassName: meu-storage