apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
  - name: giropops-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: password
    resources:
      requests:
        cpu: "0.3"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"