---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-dexter-db
data:
  create-dexter-db.sh: |-
    echo "CREATE DATABASE IF NOT EXISTS dexter CHARACTER SET utf8 COLLATE utf8_bin" | mysql --host=localhost --user=root --password=$MYSQL_ROOT_PASSWORD
    echo "GRANT ALL PRIVILEGES ON dexter.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'" | mysql --host=localhost --user=root --password=$MYSQL_ROOT_PASSWORD
