---
  image: 
    defaultImage: true
    longhorn: 
      manager: 
        repository: "longhornio/longhorn-manager"
        tag: "v1.2.4"
      engine: 
        repository: "longhornio/longhorn-engine"
        tag: "v1.2.4"
      ui: 
        repository: "longhornio/longhorn-ui"
        tag: "v1.2.4"
      instanceManager: 
        repository: "longhornio/longhorn-instance-manager"
        tag: "v1_20220303"
      shareManager: 
        repository: "longhornio/longhorn-share-manager"
        tag: "v1_20211020"
      backingImageManager: 
        repository: "longhornio/backing-image-manager"
        tag: "v2_20210820"
    csi: 
      attacher: 
        repository: "longhornio/csi-attacher"
        tag: "v3.2.1"
      provisioner: 
        repository: "longhornio/csi-provisioner"
        tag: "v2.1.2"
      nodeDriverRegistrar: 
        repository: "longhornio/csi-node-driver-registrar"
        tag: "v2.3.0"
      resizer: 
        repository: "longhornio/csi-resizer"
        tag: "v1.2.0"
      snapshotter: 
        repository: "longhornio/csi-snapshotter"
        tag: "v3.0.3"
  privateRegistry: 
    registryUrl: ""
    registryUser: ""
    registryPasswd: ""
    registrySecret: ""
  longhorn: 
    default_setting: true
  csi: 
    kubeletRootDir: ""
    attacherReplicaCount: "3"
    provisionerReplicaCount: "3"
    resizerReplicaCount: "3"
    snapshotterReplicaCount: "3"
  defaultSettings: 
    backupTarget: ""
    backupTargetCredentialSecret: ""
    allowRecurringJobWhileVolumeDetached: false
    createDefaultDiskLabeledNodes: false
    defaultDataPath: "/var/lib/longhorn/"
    defaultDataLocality: "disabled"
    replicaSoftAntiAffinity: false
    replicaAutoBalance: "disabled"
    storageOverProvisioningPercentage: "100"
    storageMinimalAvailablePercentage: "5"
    upgradeChecker: true
    defaultReplicaCount: "3"
    defaultLonghornStaticStorageClass: "longhorn-static"
    backupstorePollInterval: "300"
    autoSalvage: true
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
    disableSchedulingOnCordonedNode: true
    replicaZoneSoftAntiAffinity: true
    nodeDownPodDeletionPolicy: "do-nothing"
    allowNodeDrainWithLastHealthyReplica: false
    mkfsExt4Parameters: ""
    disableReplicaRebuild: false
    replicaReplenishmentWaitInterval: "600"
    concurrentReplicaRebuildPerNodeLimit: "5"
    disableRevisionCounter: false
    systemManagedPodsImagePullPolicy: "if-not-present"
    allowVolumeCreationWithDegradedAvailability: true
    autoCleanupSystemGeneratedSnapshot: true
    concurrentAutomaticEngineUpgradePerNodeLimit: "0"
    backingImageCleanupWaitInterval: "60"
    backingImageRecoveryWaitInterval: "300"
    guaranteedEngineManagerCPU: "12"
    guaranteedReplicaManagerCPU: "12"
  persistence: 
    defaultClass: true
    reclaimPolicy: "Delete"
    defaultClassReplicaCount: "3"
    recurringJobSelector: 
      enable: false
      jobList: ""
    backingImage: 
      enable: false
      name: ""
      expectedChecksum: ""
      dataSourceType: ""
      dataSourceParameters: ""
  ingress: 
    enabled: false
    host: "xip.io"
  service: 
    ui: 
      type: "Rancher-Proxy"
      nodePort: ""
  enablePSP: true