---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.6.18
    component: controller
    heritage: Tiller
    release: nginx-ingress
spec:
  type: NodePort 
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 31443
      protocol: TCP
  selector:
    app: nginx-ingress
    component: controller
    release: nginx-ingress
