---
apiVersion: v1
kind: LimitRange
metadata:
  name: dexter-limits1
  namespace: dexter-limits
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 0.8
    defaultRequest:
      memory: 100Mi
      cpu: 0.4
    type: Container
