---
apiVersion: v1
kind: Pod
metadata:
  name: limited-pod7
  namespace: dexter-limits
spec:
  containers:
  - name: limited-pod7
    image: nginx
    resources:
      limits:
        memory: "1.3Gi"
        cpu: 0.9
      requests:
        memory: "1Gi"
        cpu: 0.8
  nodeSelector:
    cloud: AWS
