---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/suporte/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud
          operator: In
          values:
          - AWS
